// AUTO-GENERATED by scripts/sync-prefabs.js. Do not edit by hand.
// Run `npm run sync-prefabs` after adding/removing files in /cheat-sheet-prefabs/.
//
// Image URLs are built at runtime by joining CHEAT_SHEET_PREFAB_BASE_URL (in
// shared/endpoints.ts) with each entry's relative `images` paths.

export interface PrefabPack {
  /** Stable id, derived from the directory name. */
  slug: string
  /** Display name shown in the settings UI. */
  name: string
  /** Repo-relative paths under cheat-sheet-prefabs/. */
  images: string[]
  /** When set, the pack only appears for users on the matching PoE version.
   *  Unset = visible in both. Configured via _poe.txt in the pack directory. */
  poeVersion?: 1 | 2
}

export const PREFAB_PACKS: PrefabPack[] = [
  {
    slug: 'act-1',
    name: 'Act 1',
    images: [
      'act-1/01-clearfell-1.png',
      'act-1/01-clearfell-2.png',
      'act-1/02-grelwood.png',
      'act-1/03-red-vale.png',
      'act-1/04-grim-tangle.png',
      'act-1/05-cemetery.png',
      'act-1/06-praetor.png',
      'act-1/07-consort.png',
      'act-1/08-hunting-grounds.png',
      'act-1/09-freythorn.png',
      'act-1/10-ogham-farmlands.png',
      'act-1/11-ogham-village.png',
      'act-1/12-manor-ramparts.png',
      'act-1/13-ogham-manor-1.png',
      'act-1/13-ogham-manor-2.png',
      'act-1/13-ogham-manor-3.png',
    ],
    poeVersion: 2,
  },
  {
    slug: 'act-2',
    name: 'Act 2',
    images: [
      'act-2/01-vastiri-outskirts.png',
      'act-2/02-mawdun-quarry.png',
      'act-2/03-mawdun-mine.png',
      'act-2/04-traitors-passage-1.png',
      'act-2/04-traitors-passage-2.png',
      'act-2/05-halani-gates.png',
      'act-2/06-keth.png',
      'act-2/07-lost-city.png',
      'act-2/08-buried-shrines.png',
      'act-2/09-valley-of-the-titans.png',
      'act-2/10-titan-grotto.png',
      'act-2/11-deshar.png',
      'act-2/12-path-of-mourning.png',
      'act-2/13-mastodon-badlands.png',
      'act-2/14-bone-pits.png',
      'act-2/15-spires-of-deshar.png',
      'act-2/16-dreadnought.png',
    ],
    poeVersion: 2,
  },
  {
    slug: 'act-3',
    name: 'Act 3',
    images: [
      'act-3/01-sandswept-marsh.png',
      'act-3/02-jungle-ruins-2.png',
      'act-3/03-infested-barrens.png',
      'act-3/04-chimeral-wetlands.png',
      'act-3/05-jinquanis-machinarium.png',
      'act-3/06-jinquanis-sanctum.png',
      'act-3/07-matlan-waterways.png',
      'act-3/08-apex-of-filth.png',
      'act-3/09-temple-of-kopec.png',
      'act-3/10-aggorat.png',
      'act-3/11-black-chambers.png',
      'act-3/12-azak-bog.png',
    ],
    poeVersion: 2,
  },
  {
    slug: 'act-4',
    name: 'Act 4',
    images: [
      'act-4/01-isle-of-kin.png',
      'act-4/02-volcanic-warrens.png',
      'act-4/03-kedge-bay.png',
      'act-4/04-journeys-end.png',
      'act-4/05-shrike-island.png',
      'act-4/06-whakapanu-island.png',
      'act-4/07-singing-caverns.png',
      'act-4/08-solitary-confinement.png',
      'act-4/09-eye-of-hinekora.png',
      'act-4/10-halls-of-the-dead.png',
      'act-4/11-arastas.png',
      'act-4/12-excavation.png',
      'act-4/13-ngakanu.png',
      'act-4/14-heart-of-the-tribe.png',
    ],
    poeVersion: 2,
  },
  {
    slug: 'leagues',
    name: 'Leagues',
    images: [
      'leagues/Shipments.png',
      'leagues/Syndicate-328-2552.webp',
      'leagues/Syndicate-328.webp',
      'leagues/sanctum.png',
    ],
    poeVersion: 1,
  },
]
